GET http://127.0.0.1:5000/api/id/tv43inches

###

POST http://127.0.0.1:5000/api/id/
content-type: application/json

{
  "url": "https://browser.yandex.ru/welcome-update/r/streams/",
  "custom_id": "ViI50X"
}