services:

  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - yacut_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ../../.env

  web:
    build: ../../
    restart: always
    depends_on: 
      - db
    volumes:
      - yacut_static_value:/app/yacut/static/ 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - PORT=0
    env_file:
      - ../../.env
  
  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web    
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - yacut_static_value:/var/html/static/

volumes:
  yacut_postgres_data:   
  yacut_static_value: