"""empty message

Revision ID: 11459d54f3a2
Revises: 6b20c373b328
Create Date: 2023-01-21 14:26:21.098290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11459d54f3a2'
down_revision = '6b20c373b328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_url_map_short'), 'url_map', ['short'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_map_short'), table_name='url_map')
    # ### end Alembic commands ###
